//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.CashWithdrawls = new HashSet<CashWithdrawl>();
            this.CashWithdrawls1 = new HashSet<CashWithdrawl>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AccountType { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<CashWithdrawl> CashWithdrawls { get; set; }
        public virtual ICollection<CashWithdrawl> CashWithdrawls1 { get; set; }
        public virtual AccountType AccountType1 { get; set; }
    }
}
