//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.Categories = new HashSet<Category>();
            this.MonthlyBudgets = new HashSet<MonthlyBudget>();
            this.Transactions_All = new HashSet<Transactions_All>();
        }
    
        public int Id { get; set; }
        public string BudgetName { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<MonthlyBudget> MonthlyBudgets { get; set; }
        public virtual ICollection<Transactions_All> Transactions_All { get; set; }
    }
}
