//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ExceptionTransactions = new HashSet<ExceptionTransaction>();
            this.Vendors = new HashSet<Vendor>();
            this.PurchasesByCategories = new HashSet<PurchasesByCategory>();
            this.MonthlyCategoryBudgets = new HashSet<MonthlyCategoryBudget>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Budget { get; set; }
    
        public virtual ICollection<ExceptionTransaction> ExceptionTransactions { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual ICollection<PurchasesByCategory> PurchasesByCategories { get; set; }
        public virtual Budget Budget1 { get; set; }
        public virtual ICollection<MonthlyCategoryBudget> MonthlyCategoryBudgets { get; set; }
    }
}
