//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBudget
    {
        public int Id { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Budget Budget1 { get; set; }
        public virtual Period Period1 { get; set; }
    }
}
