//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodBudgetVsActual
    {
        public int Id { get; set; }
        public int PeriodId { get; set; }
        public string PeriodName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int BudgetId { get; set; }
        public string BudgetName { get; set; }
        public double ActualAmount { get; set; }
        public Nullable<decimal> BudgetedAmount { get; set; }
        public Nullable<double> PercentOfBudget { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
