//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public Period()
        {
            this.MonthlyBudgets = new HashSet<MonthlyBudget>();
            this.MonthlyCategoryBudgets = new HashSet<MonthlyCategoryBudget>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Name { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<MonthlyBudget> MonthlyBudgets { get; set; }
        public virtual ICollection<MonthlyCategoryBudget> MonthlyCategoryBudgets { get; set; }
    }
}
