//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodBudgetVsActualSummary
    {
        public int PeriodId { get; set; }
        public Nullable<double> ActualAmount { get; set; }
        public Nullable<decimal> BudgetedAmount { get; set; }
        public Nullable<double> PercentOfBudget { get; set; }
    }
}
