//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        public TaxRate()
        {
            this.ExceptionTransactions = new HashSet<ExceptionTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ExceptionTransaction> ExceptionTransactions { get; set; }
    }
}
