//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.ExceptionTransactions = new HashSet<ExceptionTransaction>();
            this.PurchasesByCategories = new HashSet<PurchasesByCategory>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Vendor { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Account { get; set; }
        public bool Shame { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual ICollection<ExceptionTransaction> ExceptionTransactions { get; set; }
        public virtual Vendor Vendor1 { get; set; }
        public virtual ICollection<PurchasesByCategory> PurchasesByCategories { get; set; }
    }
}
