//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullshitTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions_All
    {
        public int TransactionId { get; set; }
        public int SubtransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Description { get; set; }
        public string VendorName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public string BudgetName { get; set; }
        public Nullable<double> ActualAmount { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Budget Budget { get; set; }
    }
}
